$(document).ready( function init(){

	// TODO (consider): You don't really need jquery here!
	// consider removing when optimizing site
	// IF network says its an issue

	// stores local variables which track
	// the page's state
	var locals = {};
	// stores active popin box
	locals.activeBox = undefined;
	// stores active location
	locals.iconsLocation = undefined;
	// stores whether about-skills svg lines have been drawn
	locals.svgLinesDrawn = false;
	// for about box svg lines:
	// map skills to technologies
	locals.skillsTechTable = {};
	// stores whether bandcamp iframe has been loaded
	locals.musicPlayerLoaded = false;



	// --------------------
	var $icons = $('#icons');
	var $centerpiece = $('#centerpiece');
	var $contactBox = $('#contact-box');



	var boxLocationTable = {
		'#projects-box':'left',
		'#about-box':'right',
		'#music-box':'up',
		'#websites-box':'down'
	};
	// ------------------




	// I: HELPER FUNCTIONS
	// ================================================

	// move centerpiece and popin boxes back to neutral
	var reset = function(){
		locals.iconsLocation = undefined;
		locals.activeBox = undefined;
		$contactBox.addClass('hidden');
		$centerpiece.removeClass('collapsed contact-active');
		$icons.removeClass('up down left right hidden');
		$('.active').removeClass('active');
	};

	// move centerpiece, icons, and popin boxes
	var move = function(){
		$contactBox.addClass('hidden');
		locals.iconsLocation = boxLocationTable[locals.activeBox.selector];
		$centerpiece.addClass('collapsed');
		$icons.removeClass().addClass(locals.iconsLocation);
		locals.activeBox.addClass('active').siblings().removeClass('active');
	};


	// handle clicks on icons
	var iconClickHandler = function(event){
		var id = event.currentTarget.id;
		if (id === 'about'){
			if (!locals.svgLinesDrawn){
				drawSVG();
			}
		}
		// identify popin box associated with icon id
		locals.activeBox = $('#'+id+'-box'); 
		// if box is already open, close it and move the center back to neutral
		if(locals.activeBox.hasClass('active')){
			reset();
		} else {
			move();
		}
	};

	// handle links to the contact form
	var contactBoxClickHandler = function(event){
		reset();
		$centerpiece.removeClass('collapsed').addClass('contact-active');
		$contactBox.toggleClass('hidden');
		$icons.toggleClass('hidden');
	};

	// handle swipe events generated by hammer.js
	var hammerSwipeHandler = function(event){

		// if event direction is not 'no direction'
		if(event.direction !== 1){

			// match swipe value to direction ('left','right','up','down')
			var swipe = swipeTable[event.direction];

			if (!locals.activeBox){
				$(swipe.opens).trigger('click');
			} else if (locals.activeBox.selector === swipe.closes){
				reset();
			}

		}
	};


	// draw svg lines connecting skills to technologies
	// in about-box
	function drawSVG(){


		// draws SVG lines connecting element in
		// the skill list with elements in the tech list

		// store skills and technology jQuery elements
		var skillItems = {};
		var techItems = {};
		var svgContainer = $('#svg-container');

		// if the svgs are already on the page, delete them
		if (locals.svgLinesDrawn){
			svgContainer.empty();
		}

		// match skills to technologies via IDs
		// TODO: brittle, is there a smarter way?


		// create svg object and append it to DOM
		var svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
		svg.setAttributeNS(null, 'class','about-skills-svg');
		svgContainer.append(svg);

		function drawLine(positionObj, skillID){

			var lineClass = skillID + '-line';

			var svgLine = document.createElementNS('http://www.w3.org/2000/svg','line');
			svgLine.setAttributeNS(null, 'class','about-skills-line' + ' ' + lineClass);
			svgLine.setAttributeNS(null, 'stroke-width','1px');
			//svgLine.setAttributeNS(null, 'stroke','#B7B7B7');

			svgLine.setAttributeNS(null, 'x1', positionObj.x1);
			svgLine.setAttributeNS(null, 'y1', positionObj.y1);
			svgLine.setAttributeNS(null, 'x2', positionObj.x2);
			svgLine.setAttributeNS(null, 'y2', positionObj.y2);
			svg.appendChild(svgLine);

		}


		// stick tech jQuery element into container object, we'll need it soon.
		$('#about-tech-column').find('.about-tech-item').each(function(index, elem){
			techItems[elem.id] = $(this);
		});

		// keep track of which techs map to which skills
		locals.skillTechTable = {
			'webApps': [
				techItems.javascript,
				techItems.angularJS,
				techItems.jQuery,
				techItems.html,
				techItems.css,
			],
			'restApi': [
				techItems.javascript,
				techItems.nodeJS,
				techItems.expressJS,
			],
			'server': [
				techItems.javascript,
				techItems.nodeJS,
				techItems.expressJS,
				techItems.mongoDB,
				techItems.mongoose,
				techItems.mySQL,
			],
			'webDeployment': [
				techItems.git,
				techItems.AWS,
				techItems.taskRunners,
			],
			'webDesign': [
				techItems.html,
				techItems.css,
				techItems.illustrator, 
			],
			'frontend': [
				techItems.html,
				techItems.css,
				techItems.jQuery,
				techItems.taskRunners,
			],
		};


		// iterate over skill items and draw the svgs we need.
		$('#about-skills-column').find('.about-skills-item').each(function(){
			var skillItem = $(this);
			var skillItemName = skillItem[0].id;

			// stick skill jQuery element into container object, we'll need it to
			// efficiently update the svg lines on window.resize events.
			skillItems[skillItemName] = skillItem;
			var skillPosition =  skillItem.position();


			// get the array of tech item IDs associated with this skill
			var technologies = locals.skillTechTable[skillItemName];

			var positionObj = {};
			positionObj.x1 = skillPosition.left + skillItem[0].clientWidth;
			positionObj.y1 = skillPosition.top + skillItem[0].clientHeight*0.75;
			for (var i=0;i<technologies.length;i++){

				// get position of this tech element
				var techItem = technologies[i];
				var techPosition = techItem.position();
				positionObj.x2 = techPosition.left;
				positionObj.y2 = techPosition.top + techItem[0].clientHeight*0.75;

				// draw svg line connecting skill element to tech element
				drawLine(positionObj, skillItemName);
			}
		});

		locals.svgLinesDrawn = true;
	}


	// highlight svg lines and tech boxes on associated skill hover
	function skillsItemHoverHandler(event){
		// highlight svg lines
		var skillName = event.currentTarget.id;
		var lineClass = '.' + skillName + '-line';
		$(lineClass).toggleClass('highlight');

		// highlight tech items
		var techItemsArray = locals.skillTechTable[skillName];
		for (var i=0;i<techItemsArray.length;i++){
			techItemsArray[i].toggleClass('highlight');
		}
	}
	// create iframe for bandcamp player
	function loadBandcampPlayer(){

		// DEBUG: does this block?

		// grab container
		var musicPlayerContainer = $('#music-player-container');

		// generate bandcamp player iframe
		var player = document.createElement('iframe');
		player.src = 'https://bandcamp.com/EmbeddedPlayer/album=2571936169/size=large/bgcol=ffffff/linkcol=0687f5/minimal=true/transparent=true/';
		player.setAttribute('seamless','');
		player.classList.add('music-player');

		// add link to bandcamp page to iframe
		var bcLink = document.createElement('a');
		bcLink.href = 'http://nominal.bandcamp.com/album/apartments-ep';
		player.appendChild(bcLink);

		// put iframe in container element,
		musicPlayerContainer.append(player);
		// remove loading.gif background
		musicPlayerContainer.css('background', 'none');

		// update local variable, we've loaded the player
		// locals.musicPlayerLoaded = true;
	}

	// II. EVENT HANDLERS
	// ====================

	

	
	// hammerjs initialization and swipe handlers
	// ----------------------
	var bodyContainer = document.getElementById('body-wrapper');
	var centerContainer = document.getElementById('center-container');
	var aboutBox = document.getElementById('about-box');
	var projectsBox = document.getElementById('projects-box');
	var musicBox = document.getElementById('music-box');
	var musicBoxPullTab = document.getElementById('music-box-pull-tab');
	var websitesBox = document.getElementById('websites-box');
	var websitesBoxPullTab = document.getElementById('websites-box-pull-tab');

	var hammerManagers = {};
	hammerManagers.centerContainer = new Hammer.Manager(centerContainer,{
		preset: [],
		domEvents: false,
		touchAction: 'pan-y',
		recognizers: [
			[Hammer.Swipe, {direction: Hammer.DIRECTION_ALL}]
		]
	});
	hammerManagers.aboutBox = new Hammer.Manager(aboutBox, {
		preset: [],
		domEvents: false,
		touchAction: 'pan-y',
		recognizers: [
			[Hammer.Swipe, {direction: Hammer.DIRECTION_LEFT}]
		]
	});
	hammerManagers.projectsBox = new Hammer.Manager(projectsBox, {
		preset: [],
		domEvents: false,
		touchAction: 'pan-y',
		recognizers: [
			[Hammer.Swipe, {direction: Hammer.DIRECTION_RIGHT}]
		]
	});
	hammerManagers.musicBoxPullTab = new Hammer.Manager(musicBoxPullTab, {
		preset: [],
		domEvents: false,
		touchAction: 'pan-y',
		recognizers: [
			[Hammer.Swipe, {direction: Hammer.DIRECTION_DOWN}]
		]
	});
	hammerManagers.websitesBoxPullTab = new Hammer.Manager(websitesBoxPullTab, {
		preset: [],
		domEvents: false,
		touchAction: 'pan-y',
		recognizers: [
			[Hammer.Swipe, {direction: Hammer.DIRECTION_UP}]
		]
	});

	
	var swipeTable = {
		2:{ // right swipe
			 'opens': '#projects',
			 'closes': '#about-box'
			},
		4:{ // left swipe
			'opens': '#about',
			'closes': '#projects-box'
			},
		8:{ // downward swipe
			'opens': '#music',
			'closes': '#websites-box'
			},
		16:{ // upward swipe
			'opens': '#websites',
			'closes':'#music-box'
			}
	};

	// hammerjs event handling
	// ------------------------------------
	hammerManagers.centerContainer.on('swipe', hammerSwipeHandler);
	hammerManagers.aboutBox.on('swipe', hammerSwipeHandler);
	hammerManagers.projectsBox.on('swipe', hammerSwipeHandler);
	hammerManagers.musicBoxPullTab.on('swipe', hammerSwipeHandler);
	hammerManagers.websitesBoxPullTab.on('swipe', hammerSwipeHandler);
	



	// jquery click event handlers
	// ---------------------------
	var $document = $(document);
	$document.on('click', '.contact-button', contactBoxClickHandler );
	$document.on('click', '#websites, #projects, #music, #about', iconClickHandler );
	$document.on('mouseenter mouseleave touchstart touchend', '.about-skills-item', skillsItemHoverHandler);
	$document.on('click', '#contact-cancel', reset);
	$(centerContainer).on('dblclick', reset);


	// contact-form submission event handler
	var $contactForm = $('#contact-form');
	$contactForm.on('submit', function(event){
		// stop the browser from trying to do the same thing
		event.preventDefault();
		// send the data
		$.ajax({
			type: 'POST',
			url: 'contact',
			data: $(this).serialize(),
		});
		// close the contact form
		reset();
	});

	// window event handlers
	// -----------------------------
	$(window).load(loadBandcampPlayer);
	// redraw about-skill svg lines on window resize
	window.onresize = drawSVG;
	

	// end EVENT HANDLERS
	// ======================

// end document.ready
});
